<?php

/**
 * AccountCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountCategory');
    }
}