<?php

/**
 * BonusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BonusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BonusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bonus');
    }
}