<?php

/**
 * Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    1CRegion.ru
 * @subpackage model
 * @author     Alex Kozlov <alexssource@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Comment extends BaseComment
{
    public function save(Doctrine_Connection $conn = null) {
        $this->User = sfContext::getInstance()->getUser()->getGuardUser();
        return parent::save($conn);
    }
    
    /**
     * Получение комментария исполнителя проекта
     * @param Project $project
     * @return Comment 
     */
    public static function getPerformerComment($project) {
        $q = Doctrine_Query::create()
                ->from('Comment c')
                ->where('c.project_id = ?', $project->getId())
                ->andWhere('c.is_performer = ?', true);
        return $q->fetchOne();
    }
}
