<?php

/**
 * Feedback
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    1CRegion.ru
 * @subpackage model
 * @author     Alex Kozlov <alexssource@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Feedback extends BaseFeedback
{
    /**
     * Получение всех отзывов пользователя
     * @param sfGuardUser $user
     * @return Doctrine_Collection<Feedback> 
     */
    public static function getFeedbacks(sfGuardUser $user) {
        $q = Doctrine_Core::getTable('Feedback')
                ->createQuery('f')
                ->where('f.user_id = ?', $user->getId());
        return $q->execute();
    }
    
    
    /**
     * Получение комментария
     * @param Project $project  - проект
     * @param sfGuardUser $from - от кого
     * @param sfGuardUser $to   - кому
     * @return Feedback
     */
    public static function getFeedback($project, $from, $to) {
        $q = Doctrine_Query::create()
                ->from('Feedback f')
                ->where('f.project_id = ?', $project->getId())
                ->andWhere('f.owner_id = ?', $from->getId())
                ->andWhere('f.user_id = ?', $to->getId());
        return $q->fetchOne();
    }
}
