<?php

/**
 * Messages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    1CRegion.ru
 * @subpackage model
 * @author     Alex Kozlov <alexssource@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Messages extends BaseMessages
{
    public function save(Doctrine_Connection $conn = null) {
        $this->From = sfContext::getInstance()->getUser()->getGuardUser();
        return parent::save($conn);
    }
    
    public static function getUserContacts($user_id) {
        $q = MessagesTable::getInstance()->createQuery('m')
                ->where('m.to_id = ?', $user_id)
                ->groupBy('m.from_id')
                ->orderBy('m.created_at');
        return $q->execute();
    }
    
    public static function getUserUnreadMessages($user_id) {
        $q = MessagesTable::getInstance()->createQuery('m')
                ->select('m.from_id')
                ->where('m.to_id = ?', $user_id)
                ->andWhere('m.is_read = 0')
                ->groupBy('m.from_id');
        return $q->fetchArray();
    }
    
    
    public function hasUnread() {
        $q = $this->getTable()->createQuery('c')
                ->where('c.from_id = ?', $this->getFromId())
                ->andWhere('c.to_id = ?', $this->getToId())
                ->andWhere('c.is_read = ?', false)
                ->fetchOne();
        return ($q != null);
    }
    
    
    public static function getUserMessages($user_id, $from_id) {
        $q = MessagesTable::getInstance()->createQuery('m')
/*
                ->whereIn('m.from_id = '.$user_id, array($user_id, $from_id))
                ->andWhereIn('m.to_id = '.$user_id, array($user_id, $from_id))
 */
                ->where('(m.from_id = ? OR m.from_id = ?) AND (m.to_id = ? OR m.to_id = ?)', array($from_id, $user_id, $from_id, $user_id))
                ->orderBy('m.created_at asc');
        return $q->execute();
    }
}
