<?php

/**
 * PortfolioWork
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    1CRegion.ru
 * @subpackage model
 * @author     Alex Kozlov <alexssource@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PortfolioWork extends BasePortfolioWork
{
    public function save(Doctrine_Connection $conn = null) {
        $this->User = sfContext::getInstance()->getUser()->getGuardUser();
        return parent::save($conn);
    }
    
    public function getUsername() {
        return $this->User->getUsername();
    }
    
    public static function getUserWorks($user_id) {
        $q = PortfolioWorkTable::getInstance()->createQuery('w')
                ->where('w.user_id = ?', $user_id)
                ->orderBy('w.category_id');
        return $q->execute();
    }
}
