<?php

/**
 * PortfolioWorkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PortfolioWorkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PortfolioWorkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PortfolioWork');
    }
}