<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addbonus extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('bonus', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'unique' => true,
              'primary' => true,
              'length' => 8,
             ),
             'bonus' => 
             array(
              'type' => 'float',
              'notnull' => true,
              'default' => 50,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'user_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('bonus');
    }
}