<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcomment extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('comment', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'project_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'cost' => 
             array(
              'type' => 'float',
              'length' => 7,
             ),
             'currency_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'cost_type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'цена за час',
              1 => 'цена за день',
              2 => 'цена за месяц',
              3 => 'цена за проект',
              ),
              'default' => 'цена за проект',
              'length' => NULL,
             ),
             'term' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'length' => 8,
             ),
             'term_options' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'Час',
              1 => 'День',
              2 => 'Неделя',
              3 => 'Месяц',
              4 => 'Год',
              ),
              'notnull' => true,
              'default' => 'День',
              'length' => NULL,
             ),
             'is_security_deal' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'default' => 0,
              'length' => 25,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'default' => 1,
              'length' => 25,
             ),
             'is_candidate' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'default' => 0,
              'length' => 25,
             ),
             'is_performer' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'default' => 0,
              'length' => 25,
             ),
             'comment' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 1000,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('comment');
    }
}