<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfeedback extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('feedback', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'owner_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'project_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'feedback_type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'positive',
              1 => 'negative',
              ),
              'notnull' => true,
              'default' => 'positive',
              'length' => NULL,
             ),
             'cost' => 
             array(
              'type' => 'float',
              'length' => 8,
              'notnull' => true,
              'default' => '0.00',
             ),
             'ball' => 
             array(
              'type' => 'integer',
              'length' => 2,
              'notnull' => true,
              'default' => 0,
             ),
             'comment' => 
             array(
              'type' => 'text',
              'notnull' => true,
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('feedback');
    }
}