<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addportfoliowork extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('portfolio_work', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 4000,
             ),
             'category_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'image' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'link' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'cost' => 
             array(
              'type' => 'float',
              'length' => 8,
             ),
             'cost_currency_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'term' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'term_options' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'Час',
              1 => 'День',
              2 => 'Неделя',
              3 => 'Месяц',
              4 => 'Год',
              ),
              'notnull' => true,
              'default' => 'День',
              'length' => NULL,
             ),
             'file_src' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('portfolio_work');
    }
}