Project:
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [name]
      builder: ['tsDoctrineInflector', 'urlize']
    
  columns:
    name:  { type: string(80), notnull: true }
    small_description: { type: string(100), notnull: true }
    description: { type: string(2000), notnull: true }
    file_src: { type: string(255) }
    category_id: { type: integer, notnull: true }
    work_type: { type: enum, values: ['Проекты', 'В офис'], default: 'Проекты' }
    office_country_id: { type: integer }
    office_region_id: { type: integer }
    office_city_id: { type: integer }
    is_budget_by_agreement: { type: boolean, notnull: true, default: false }
    budget: { type: float, length: 8, notnull: true, default: 0.00 }
    budget_currency_id: { type: integer }
    budget_type: { type: enum, values: ['цена за час', 'цена за день', 'цена за месяц', 'цена за проект'], default: 'цена за проект' }
    is_security_deal: { type: boolean, notnull: true, default: false }
    expires_at: { type: timestamp, notnull: true }
    term: { type: integer }
    term_options: { type: enum, values: ['Час','День', 'Неделя', 'Месяц', 'Год'], notnull: true, default: 'День' }
    owner_id: { type: integer, notnull: true }
    is_active: { type: boolean, notnull: true, default: true }
      
  relations:
    Category:
      class: Category
      local: category_id
      foreign: id
      foreignAlias: Projects
    OfficeCountry:
      class: Country
      local: office_country_id
      foreign: id
      foreignAlias: Projects
    OfficeRegion:
      class: Region
      local: office_region_id
      foreign: id
      foreignAlias: Projects
    OfficeCity:
      class: City
      local: office_city_id
      foreign: id
      foreignAlias: Projects
    BudgetCurrency:
      class: Currency
      local: budget_currency_id
      foreign: id
      foreignAlias: Projects
    User:
      class: sfGuardUser
      local: owner_id
      foreign: id
      foreignAlias: Projects
      
  options:
    charset: utf8