Region:
  actAs:
    Sluggable:
      fields: [name]
      builder: ['tsDoctrineInflector', 'urlize']
  columns:
    country_id: { type: integer, notnull: true }
    name: { type: string(255), notnull: true, unique: true }
  relations:
    Country:
      class: Country
      local: country_id
      foreign: id
      foreignAlias: Region
  options:
    charset: utf8